version: '2'

services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: unless-stopped
    image: postgres:14.1
    expose:
      - '5432'
  redis:
    restart: unless-stopped
    image: redis:6.2
    expose:
      - '6379'
  app:
    environment:
      DJANGO_SECRET_KEY: changeme
      DATABASE_URL: postgres://app_user:changeme@db/app_db
      CACHE_URL: redis://redis
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - static_volume:/code/mysite/collect_static
      - media_volume:/code/mysite/media/images
    links:
      - db:db
      - redis:redis
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
  nginx:
    container_name: Nginx
    build: ./nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/code/mysite/collect_static
      - media_volume:/code/mysite/media/images
    depends_on:
      - app

volumes:
  static_volume:
  media_volume:
